spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        # User Service Routes
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: user-service-swagger
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**

        # Content Service Routes
        - id: pins-service-route
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/api/v1/pins/**

        - id: boards-service-route
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/api/v1/boards/**

        - id: tags-service-route
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/api/v1/tags/**

        - id: content-service-swagger
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/content-service/**

        # Social Service Routes
        - id: comments-service-route
          uri: lb://SOCIAL-SERVICE
          predicates:
            - Path=/api/v1/comments/**

        - id: likes-service-route
          uri: lb://SOCIAL-SERVICE
          predicates:
            - Path=/api/v1/likes/**

        - id: subscriptions-service-route
          uri: lb://SOCIAL-SERVICE
          predicates:
            - Path=/api/v1/subscriptions/**

        - id: social-service-swagger
          uri: lb://SOCIAL-SERVICE
          predicates:
            - Path=/social-service/**

        # Chat Service Routes
        - id: chat-service-route
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/v1/chats/**

        - id: chat-websocket-route
          uri: lb:ws://CHAT-SERVICE
          predicates:
            - Path=/ws/chat/**

        - id: chat-service-swagger
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/**

        # Notification Service Routes
        - id: notification-service-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**

        - id: notification-websocket-route
          uri: lb:ws://NOTIFICATION-SERVICE
          predicates:
            - Path=/ws/notifications/**

        - id: notification-service-swagger
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/**

        # Recommendation Service Routes
        - id: recommendation-service-route
          uri: lb://RECOMMENDATION-SERVICE
          predicates:
            - Path=/api/v1/recommendations/**

        - id: recommendation-service-swagger
          uri: lb://RECOMMENDATION-SERVICE
          predicates:
            - Path=/recommendation-service/**

        # Search Service Routes
        - id: search-service-route
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/api/v1/search/**

        - id: search-service-swagger
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search-service/**

        # Media Service Routes
        - id: media-service-route
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/api/v1/media/**

        - id: media-service-swagger
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/media-service/**

        # Admin Service Routes
        - id: admin-service-route
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/v1/admin/**

        - id: admin-service-swagger
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin-service/**


      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - TokenRelay=

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://localhost:80"
              - "https://localhost:443"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: api-gateway
        url: /v3/api-docs

      - name: user-service
        url: /user-service/v3/api-docs

      - name: content-service
        url: /content-service/v3/api-docs

      - name: social-service
        url: /social-service/v3/api-docs

      - name: chat-service
        url: /chat-service/v3/api-docs

      - name: notification-service
        url: /notification-service/v3/api-docs

      - name: recommendation-service
        url: /recommendation-service/v3/api-docs

      - name: search-service
        url: /search-service/v3/api-docs

      - name: media-service
        url: /media-service/v3/api-docs

      - name: admin-service
        url: /admin-service/v3/api-docs

server:
  port: 8222
