spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        # ==================== User Service Routes ====================
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: subscriptions-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/subscriptions/**

        - id: user-service-swagger
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**

        # ==================== Content Service Routes ====================
        - id: pins-service-route
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/api/v1/pins/**

        - id: boards-service-route
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/api/v1/boards/**

        - id: comments-service-route
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/api/v1/comments/**

        - id: tags-service-route
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/api/v1/tags/**

        - id: content-service-swagger
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/content-service/**

        # ==================== Chat Service Routes ====================
        - id: chat-websocket-info
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/ws/chat/info

        - id: chat-presence-route
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/v1/presence/**

        - id: chat-service-route
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/v1/chats/**

        - id: chat-websocket-route
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/ws/chat/**

        - id: chat-service-swagger
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/**

        # ==================== Notification Service Routes ====================
        - id: notification-sse-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/sse/**
          metadata:
            response-timeout: -1
            connect-timeout: 10000

        - id: notification-service-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**

        - id: notification-service-swagger
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/**

        # ==================== Recommendation Service Routes ====================
        - id: recommendation-service-route
          uri: lb://RECOMMENDATION-SERVICE
          predicates:
            - Path=/api/v1/recommendations/**

        - id: recommendation-service-swagger
          uri: lb://RECOMMENDATION-SERVICE
          predicates:
            - Path=/recommendation-service/**

        # ==================== Search Service Routes ====================
        - id: search-service-route
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/api/v1/search/**

        - id: search-service-swagger
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search-service/**

        # ==================== Storage Service Routes ====================
        - id: storage-service-route
          uri: lb://STORAGE-SERVICE
          predicates:
            - Path=/api/v1/images/**

        - id: storage-service-swagger
          uri: lb://STORAGE-SERVICE
          predicates:
            - Path=/storage-service/**

        # ==================== Admin Service Routes ====================
        - id: admin-service-route
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/v1/admin/**

        - id: admin-service-swagger
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin-service/**

      httpclient:
        connect-timeout: 5000
        response-timeout: 30s

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - TokenRelay=

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: api-gateway
        url: /v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: content-service
        url: /content-service/v3/api-docs
      - name: storage-service
        url: /storage-service/v3/api-docs
      - name: chat-service
        url: /chat-service/v3/api-docs
      - name: notification-service
        url: /notification-service/v3/api-docs

server:
  port: 8222
