spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/content}
    username: ${SPRING_DATASOURCE_USERNAME:username}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

file:
  upload-dir: ./uploads
  allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx,txt
  max-size: 10485760

server:
  port: 8020