spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}
    connection-timeout: 5s
    socket-timeout: 30s

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: search-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

# Kafka topics
kafka:
  topics:
    content-events: content-events
    user-events: user-events

# Search settings
search:
  default-page-size: 20
  max-page-size: 100
  highlight:
    pre-tag: "<em>"
    post-tag: "</em>"
  fuzzy:
    enabled: true
    max-expansions: 50
    prefix-length: 2

# Index settings
index:
  pins:
    name: pins
  users:
    name: users
  boards:
    name: boards
  search-analytics:
    name: search_analytics
  search-history:
    name: search_history
  trending-queries:
    name: trending_queries
  user-interests:
    name: user_interests

# Personalization settings
personalization:
  enabled: true
  max-tags: 50
  max-authors: 100
  decay-factor: 0.95

# Analytics cleanup
analytics:
  cleanup:
    retention-days: 30

server:
  port: 8050