spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2MB

minio:
  endpoint: http://localhost:9000
  bucketName: images
  thumbnailBucket: thumbnails
  accessKey: root
  secretKey: password

image-storage:
  max-file-size: 10485760  # 10MB
  allowed-content-types: image/jpeg,image/jpg,image/png,image/gif,image/webp
  url-expiry-days: 7

server:
  port: 8088