# config-server/src/main/resources/configurations/storage-service.yml

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/storage_db}
    username: ${SPRING_DATASOURCE_USERNAME:storage_user}
    password: ${SPRING_DATASOURCE_PASSWORD:storage123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  bucketName: ${MINIO_BUCKET:images}
  thumbnailBucket: ${MINIO_THUMBNAIL_BUCKET:thumbnails}
  accessKey: ${MINIO_ACCESS_KEY:admin}
  secretKey: ${MINIO_SECRET_KEY:minio123}

image-storage:
  max-file-size: 10485760  # 10MB
  allowed-content-types: image/jpeg,image/jpg,image/png,image/gif,image/webp
  presigned-url-expiry-minutes: 15
  download-url-expiry-hours: 24
  cleanup:
    enabled: true
    interval-ms: 3600000  # 1 hour
    pending-expiry-hours: 2

server:
  port: 8088